[package]
name = "pktparse"
version = "0.3.0"
authors = ["Nathan Moos", "Xavier Bestel"]
description = "Collection of packet parsers"
repository = "https://github.com/bestouff/pktparse-rs"
readme = "README.md"
license = "LGPL-3.0"

[features]
derive = ["serde", "serde_derive"]

[dependencies]
nom = "4.0"
arrayref = "0.3.2"

serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
